// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"

	"example.com/app-api/util"
	"example.com/app-api/util/jsql"
)

func (r *UserStoreImpl) Get(ctx context.Context, id int64) (*User, error) {
	qry := "SELECT\n  " + r.qrySelectObj() + "\nFROM\n  " + r.qryFromObj() + "\nWHERE\n" +
		`obj.id = $1`
	var obj User
	slog.Debug("store.User.Get", slog.String("qry", qry), slog.Int64("id", id))
	rows, err := r.db.QueryContext(ctx, qry, id)
	if err != nil {
		slog.Error("store.User.Get", slog.String("qry", qry), slog.Int64("id", id), slog.Any("Error", err))
		return nil, err
	}
	defer rows.Close()
	if rows.Next() {
		err = r.scanObj(&obj, rows)
		if err != nil {
			slog.Error("store.User.Get.Scan", slog.String("qry", qry), slog.Int64("id", id), slog.Any("Error", err))
			return nil, err
		}
	} else {
		return nil, fmt.Errorf("NOT_FOUND")
	}
	obj.Roles, err = r.getObj_Roles(ctx, obj)
	if err != nil {
		return nil, err
	}
	return &obj, err
}

func (r *UserStoreImpl) GetByEmail(ctx context.Context, email string) (*User, error) {
	qry := "SELECT\n  " + r.qrySelectObj() + "\nFROM\n  " + r.qryFromObj() + "\nWHERE\n  " +
		`obj.email = $1`
	var obj User
	slog.Debug("store.Email.Get", slog.String("qry", qry), slog.String("email", email))
	rows, err := r.db.QueryContext(ctx, qry, email)
	if err != nil {
		slog.Error("store.Email.Get", slog.String("qry", qry), slog.String("email", email), slog.Any("Error", err))
		return nil, err
	}
	defer rows.Close()
	if rows.Next() {
		err = r.scanObj(&obj, rows)
		if err != nil {
			slog.Error("store.Email.Get", slog.String("qry", qry), slog.String("email", email), slog.Any("Error", err))
			return nil, err
		}
	} else {
		return nil, fmt.Errorf("NOT_FOUND")
	}
	obj.Roles, err = r.getObj_Roles(ctx, obj)
	if err != nil {
		return nil, err
	}
	return &obj, nil
}

func qrySelectCountObj_User() string {
	return `COUNT(DISTINCT
  obj.id)`
}

func qrySelectObj_User() string {
	return `obj.id,
      obj.email,
      obj.version,
      obj.name,
      obj.password,
      obj.token,
      obj.secret,
      objCreatedBy.id,
      objCreatedBy.name,
      objCreatedBy.email,
      obj.created_at,
      objUpdatedBy.id,
      objUpdatedBy.name,
      objUpdatedBy.email,
      obj.updated_at`
}

func qryFromObj_User() string {
	return `((app_user obj LEFT JOIN app_user objCreatedBy ON obj.created_by = objCreatedBy.id)
      LEFT JOIN app_user objUpdatedBy ON obj.updated_by = objUpdatedBy.id)`
}

func scanObj_User(obj *User, rows *sql.Rows) error {
	var err error
	var refCreatedBy_ID jsql.NullInt64
	var refCreatedBy_Name jsql.NullString
	var refCreatedBy_Email jsql.NullString
	var refUpdatedBy_ID jsql.NullInt64
	var refUpdatedBy_Name jsql.NullString
	var refUpdatedBy_Email jsql.NullString
	err = rows.Scan(
		&obj.ID,
		&obj.Email,
		&obj.Version,
		&obj.Name,
		&obj.Password,
		&obj.Token,
		&obj.Secret,
		&refCreatedBy_ID,
		&refCreatedBy_Name,
		&refCreatedBy_Email,
		&obj.CreatedAt,
		&refUpdatedBy_ID,
		&refUpdatedBy_Name,
		&refUpdatedBy_Email,
		&obj.UpdatedAt)
	if err != nil {
		return err
	}
	obj.CreatedAt = util.AsZoneWallClock(obj.CreatedAt)
	obj.UpdatedAt = util.AsZoneWallClock(obj.UpdatedAt)
	if refCreatedBy_ID.Valid {
		if obj.CreatedBy == nil {
			obj.CreatedBy = &UserRef{ID: refCreatedBy_ID.Int64}
		} else {
			obj.CreatedBy.ID = refCreatedBy_ID.Int64
		}
	}
	if refCreatedBy_Name.Valid {
		obj.CreatedBy.Name = refCreatedBy_Name.String
	}
	if refCreatedBy_Email.Valid {
		obj.CreatedBy.Email = refCreatedBy_Email.String
	}
	if refUpdatedBy_ID.Valid {
		if obj.UpdatedBy == nil {
			obj.UpdatedBy = &UserRef{ID: refUpdatedBy_ID.Int64}
		} else {
			obj.UpdatedBy.ID = refUpdatedBy_ID.Int64
		}
	}
	if refUpdatedBy_Name.Valid {
		obj.UpdatedBy.Name = refUpdatedBy_Name.String
	}
	if refUpdatedBy_Email.Valid {
		obj.UpdatedBy.Email = refUpdatedBy_Email.String
	}
	return err
}

func getObj_User_Roles(r *UserStoreImpl, ctx context.Context, obj User) ([]Role, error) {
	var err error
	qry := `SELECT
      id,
      name,
      privileges
    FROM
      app_role obj JOIN app_user_role objRef ON
        obj.id = objRef.app_role
    WHERE
        objRef.app_user = $1`
	slog.Debug("store.Roles.Get", slog.String("qry", qry), slog.Int64("ID", obj.ID))
	rows, err := r.db.QueryContext(ctx, qry, obj.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var list []Role
	for rows.Next() {
		var ref Role
		err = rows.Scan(
			&ref.ID,
			&ref.Name,
			&ref.Privileges,
		)
		if err != nil {
			return nil, err
		}
		list = append(list, ref)
	}
	return list, err
}
