// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
)

func (r *UserStoreImpl) Delete(ctx context.Context, id int64) error {
	var tx *sql.Tx
	var err error
	var txNew bool
	tx, err = r.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	txNew = true
	qry := `
    DELETE FROM app_user obj WHERE
      obj.id = $1`
	slog.Debug("store.User.Delete", "qry", qry, "id", id)
	res, err := tx.ExecContext(ctx, qry, id)
	if err != nil {
		return deletePostgresError(r.db, "store.User.Delete", err,
			slog.String("qry", qry), "id", id,
		)
	}
	ra, err := res.RowsAffected()
	if err != nil {
		return deletePostgresError(r.db, "store.User.Delete.RowsAffected", err,
			slog.String("qry", qry), "id", id,
		)
	}
	if ra == 0 {
		return fmt.Errorf("NO_ROWS_AFFECTED")
	}
	if ra != 1 {
		return fmt.Errorf("invalid rows affected (%d)", ra)
	}
	if txNew {
		err = tx.Commit()
		if err != nil {
			return err
		}
	}
	return nil
}
