// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"database/sql"
	"encoding/json"

	"example.com/app-api/util"
)

type Store interface {
	Param() ParamStore
	Role() RoleStore
	User() UserStore
}

type StoreImpl struct {
	db *sql.DB
}

func GetStore() Store {
	return &StoreImpl{
		db: util.GetPostgresConn("DB"),
	}
}

type FilterOp string

const (
	FilterOp_EQ        FilterOp = "eq"
	FilterOp_Like      FilterOp = "like"
	FilterOp_ILike     FilterOp = "ilike"
	FilterOp_Greater   FilterOp = "gt"
	FilterOp_Less      FilterOp = "lt"
	FilterOp_GreaterEq FilterOp = "gte"
	FilterOp_LessEq    FilterOp = "lte"
)

type SortDir string

const (
	SortDir_ASC  SortDir = "asc"
	SortDir_DESC SortDir = "desc"
)

type FilterFn func(qfilter []string, args []any, field string, op FilterOp, value json.RawMessage) ([]string, []any, error)

type FilterFieldFn func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error)
