// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"
)

func (r *RoleStoreImpl) Update(ctx context.Context, obj Role, fields []RoleField) error {
	var tx *sql.Tx
	var err error
	var txNew bool
	tx, err = r.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	txNew = true
	defer tx.Rollback()
	args := []any{}
	qry := `UPDATE app_role SET`
	for _, f := range fields {
		switch f {
		case RoleField_Name:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.Name)
			qry += fmt.Sprintf("  name = $%d", len(args))
		case RoleField_Description:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.Description)
			qry += fmt.Sprintf("  description = $%d", len(args))
		case RoleField_Privileges:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.Privileges)
			qry += fmt.Sprintf("  privileges = $%d", len(args))
		case RoleField_UpdatedBy:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.UpdatedBy)
			qry += fmt.Sprintf("  modified_by = $%d", len(args))
		case RoleField_UpdatedAt:
			if len(args) > 0 {
				qry += ","
			}
			args = append(args, obj.UpdatedAt)
			qry += fmt.Sprintf("  modified_date = $%d", len(args))
		default:
			return fmt.Errorf("field %v is unknown", f)
		}
	}
	qry += "\nWHERE\n"
	args = append(args, obj.ID)
	qry += fmt.Sprintf("  id = $%d", len(args))

	slog.Debug("store.Role.Update", logQueryArgs(qry, args, nil)...)
	res, err := tx.ExecContext(ctx, qry, args...)
	if err != nil {
		nargs := append(append([]any{}, "qry", qry), args...)
		return updatePostgresError(r.db, "store.Role.Update", err, nargs...)
	}
	ra, err := res.RowsAffected()
	if err != nil {
		nargs := append(append([]any{}, "qry", qry), args...)
		return updatePostgresError(r.db, "store.Role.Update.RowsAffected", err, nargs...)
	}
	if ra == 0 {
		return fmt.Errorf("NO_ROWS_AFFECTED")
	}
	if ra != 1 {
		return fmt.Errorf("invalid rows affected (%d)", ra)
	}
	if txNew {
		err = tx.Commit()
		if err != nil {
			return err
		}
	}
	return nil
}
