// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"fmt"
	"strings"
)

type ErrorDuplicate struct {
	Table      string
	Constraint string
	Cols       []string
	Msg        string
}

func (e *ErrorDuplicate) Error() string {
	if len(e.Cols) > 0 {
		return fmt.Sprintf("duplicate value for %s (constraint=%s) (%s)", e.Table, e.Constraint, strings.Join(e.Cols, ", "))
	}
	return fmt.Sprintf("duplicate value in %s (constraint=%s)", e.Table, e.Constraint)
}
