// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"encoding/json"
	"time"

	"example.com/app-api/util"
	"example.com/app-api/util/jsql"
)

// swagger: model UserRef
type UserRef struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Version   int64     `json:"version"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// swagger: model User
type User struct {
	ID        int64       `json:"id"`
	Email     string      `json:"email"`
	Version   int64       `json:"version"`
	Name      string      `json:"name"`
	Password  jsql.Secret `json:"password"`
	Token     jsql.Secret `json:"token"`
	Secret    jsql.Secret `json:"secret"`
	Roles     []Role      `json:"roles"`
	CreatedBy *UserRef    `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedBy *UserRef    `json:"updated_by"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type UserField string

const (
	UserField_ID        UserField = "id"
	UserField_Email     UserField = "email"
	UserField_Version   UserField = "version"
	UserField_Name      UserField = "name"
	UserField_Password  UserField = "password"
	UserField_Token     UserField = "token"
	UserField_Secret    UserField = "secret"
	UserField_Roles     UserField = "roles"
	UserField_CreatedBy UserField = "created_by"
	UserField_CreatedAt UserField = "created_at"
	UserField_UpdatedBy UserField = "updated_by"
	UserField_UpdatedAt UserField = "updated_at"
)

// swagger: model UserSorting
type UserSorting struct {
	Field UserField `json:"field"`
	Dir   SortDir   `json:"dir"`
}

// swagger: model UserFilter
type UserFilter struct {
	Field UserField       `json:"field"`
	Op    FilterOp        `json:"op"`
	Value json.RawMessage `json:"value"`
}

func (m *User) VerifyPassword(value string) (bool, error) {
	return util.VerifyPassword(value, m.Password)
}
