// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"

	"example.com/app-api/util"
)

func (r *RoleStoreImpl) Get(ctx context.Context, id int64) (*Role, error) {
	qry := "SELECT\n  " + r.qrySelectObj() + "\nFROM\n  " + r.qryFromObj() + "\nWHERE\n" +
		`obj.id = $1`
	var obj Role
	slog.Debug("store.Role.Get", slog.String("qry", qry), slog.Int64("id", id))
	rows, err := r.db.QueryContext(ctx, qry, id)
	if err != nil {
		slog.Error("store.Role.Get", slog.String("qry", qry), slog.Int64("id", id), slog.Any("Error", err))
		return nil, err
	}
	defer rows.Close()
	if rows.Next() {
		err = r.scanObj(&obj, rows)
		if err != nil {
			slog.Error("store.Role.Get.Scan", slog.String("qry", qry), slog.Int64("id", id), slog.Any("Error", err))
			return nil, err
		}
	} else {
		return nil, fmt.Errorf("NOT_FOUND")
	}
	return &obj, err
}

func (r *RoleStoreImpl) GetByName(ctx context.Context, name string) (*Role, error) {
	qry := "SELECT\n  " + r.qrySelectObj() + "\nFROM\n  " + r.qryFromObj() + "\nWHERE\n  " +
		`obj.name = $1`
	var obj Role
	slog.Debug("store.Name.Get", slog.String("qry", qry), slog.String("name", name))
	rows, err := r.db.QueryContext(ctx, qry, name)
	if err != nil {
		slog.Error("store.Name.Get", slog.String("qry", qry), slog.String("name", name), slog.Any("Error", err))
		return nil, err
	}
	defer rows.Close()
	if rows.Next() {
		err = r.scanObj(&obj, rows)
		if err != nil {
			slog.Error("store.Name.Get", slog.String("qry", qry), slog.String("name", name), slog.Any("Error", err))
			return nil, err
		}
	} else {
		return nil, fmt.Errorf("NOT_FOUND")
	}
	return &obj, nil
}

func qrySelectCountObj_Role() string {
	return `COUNT(DISTINCT
  obj.id)`
}

func qrySelectObj_Role() string {
	return `obj.id,
      obj.name,
      obj.description,
      obj.privileges,
      obj.modified_by,
      obj.modified_date`
}

func qryFromObj_Role() string {
	return `app_role obj`
}

func scanObj_Role(obj *Role, rows *sql.Rows) error {
	var err error

	err = rows.Scan(
		&obj.ID,
		&obj.Name,
		&obj.Description,
		&obj.Privileges,
		&obj.UpdatedBy,
		&obj.UpdatedAt)
	if err != nil {
		return err
	}
	obj.UpdatedAt = util.AsZoneWallClock(obj.UpdatedAt)
	return err
}
