// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"context"
	"database/sql"
	"encoding/json"
)

type ParamStore interface {
	Create(ctx context.Context, obj Param) (*Param, error)
	Get(ctx context.Context, id int64) (*Param, error)
	GetByPARAM_UNIQUE(ctx context.Context, code string, group_name string) (*Param, error)
	FindOne(ctx context.Context, filter []ParamFilter, sorting []ParamSorting) (*Param, error)
	Find(ctx context.Context, filter []ParamFilter, sorting []ParamSorting, limit int, offset int64) ([]Param, int64, error)
	Update(ctx context.Context, obj Param, fields []ParamField) error
	Delete(ctx context.Context, id int64) error
}

type ParamStoreImpl struct {
	*StoreImpl
	fields            map[ParamField]string
	findFilters       map[ParamField]FilterFieldFn
	qrySelectCountObj func() string
	qrySelectObj      func() string
	qryFromObj        func() string
	scanObj           func(obj *Param, rows *sql.Rows) error
}

func (r *StoreImpl) Param() ParamStore {
	robj := &ParamStoreImpl{
		StoreImpl:         r,
		qrySelectCountObj: qrySelectCountObj_Param,
		qrySelectObj:      qrySelectObj_Param,
		qryFromObj:        qryFromObj_Param,
		scanObj:           scanObj_Param,
	}
	robj.fields = make(map[ParamField]string)
	robj.fields[ParamField_ID] = "id"
	robj.fields[ParamField_Group] = "group_name"
	robj.fields[ParamField_Code] = "code"
	robj.fields[ParamField_Value] = "value"
	robj.fields[ParamField_Description] = "description"
	robj.fields[ParamField_UpdatedBy] = "modified_by"
	robj.fields[ParamField_UpdatedAt] = "modified_date"
	robj.findFilters = make(map[ParamField]FilterFieldFn)
	robj.findFilters[ParamField_ID] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresInt(qfilter, args, "obj.id", op, value)
	}
	robj.findFilters[ParamField_Group] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresText(qfilter, args, "obj.group_name", op, value)
	}
	robj.findFilters[ParamField_Code] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresText(qfilter, args, "obj.code", op, value)
	}
	robj.findFilters[ParamField_Value] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresText(qfilter, args, "obj.value", op, value)
	}
	robj.findFilters[ParamField_Description] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresText(qfilter, args, "obj.description", op, value)
	}
	robj.findFilters[ParamField_UpdatedBy] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresText(qfilter, args, "obj.modified_by", op, value)
	}
	robj.findFilters[ParamField_UpdatedAt] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresTime(qfilter, args, "obj.modified_date", op, value)
	}
	return robj
}
