// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"context"
	"database/sql"
	"encoding/json"
)

type RoleStore interface {
	Create(ctx context.Context, obj Role) (*Role, error)
	Get(ctx context.Context, id int64) (*Role, error)
	GetByName(ctx context.Context, name string) (*Role, error)
	FindOne(ctx context.Context, filter []RoleFilter, sorting []RoleSorting) (*Role, error)
	Find(ctx context.Context, filter []RoleFilter, sorting []RoleSorting, limit int, offset int64) ([]Role, int64, error)
	Update(ctx context.Context, obj Role, fields []RoleField) error
	Delete(ctx context.Context, id int64) error
}

type RoleStoreImpl struct {
	*StoreImpl
	fields            map[RoleField]string
	findFilters       map[RoleField]FilterFieldFn
	qrySelectCountObj func() string
	qrySelectObj      func() string
	qryFromObj        func() string
	scanObj           func(obj *Role, rows *sql.Rows) error
}

func (r *StoreImpl) Role() RoleStore {
	robj := &RoleStoreImpl{
		StoreImpl:         r,
		qrySelectCountObj: qrySelectCountObj_Role,
		qrySelectObj:      qrySelectObj_Role,
		qryFromObj:        qryFromObj_Role,
		scanObj:           scanObj_Role,
	}
	robj.fields = make(map[RoleField]string)
	robj.fields[RoleField_ID] = "id"
	robj.fields[RoleField_Name] = "name"
	robj.fields[RoleField_Description] = "description"
	robj.fields[RoleField_Privileges] = "privileges"
	robj.fields[RoleField_UpdatedBy] = "modified_by"
	robj.fields[RoleField_UpdatedAt] = "modified_date"
	robj.findFilters = make(map[RoleField]FilterFieldFn)
	robj.findFilters[RoleField_ID] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresInt(qfilter, args, "obj.id", op, value)
	}
	robj.findFilters[RoleField_Name] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresText(qfilter, args, "obj.name", op, value)
	}
	robj.findFilters[RoleField_Description] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresText(qfilter, args, "obj.description", op, value)
	}
	robj.findFilters[RoleField_UpdatedBy] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresText(qfilter, args, "obj.modified_by", op, value)
	}
	robj.findFilters[RoleField_UpdatedAt] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresTime(qfilter, args, "obj.modified_date", op, value)
	}
	return robj
}
