// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"encoding/json"
	"time"

	"example.com/app-api/util/jsql"
)

// swagger: model Role
type Role struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description jsql.NullString `json:"description"`
	Privileges  string          `json:"privileges"`
	UpdatedBy   string          `json:"modified_by"`
	UpdatedAt   time.Time       `json:"modified_date"`
}

type RoleField string

const (
	RoleField_ID          RoleField = "id"
	RoleField_Name        RoleField = "name"
	RoleField_Description RoleField = "description"
	RoleField_Privileges  RoleField = "privileges"
	RoleField_UpdatedBy   RoleField = "modified_by"
	RoleField_UpdatedAt   RoleField = "modified_date"
)

// swagger: model RoleSorting
type RoleSorting struct {
	Field RoleField `json:"field"`
	Dir   SortDir   `json:"dir"`
}

// swagger: model RoleFilter
type RoleFilter struct {
	Field RoleField       `json:"field"`
	Op    FilterOp        `json:"op"`
	Value json.RawMessage `json:"value"`
}
