// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"context"
	"database/sql"
	"encoding/json"
)

type UserStore interface {
	Create(ctx context.Context, obj User) (*User, error)
	Get(ctx context.Context, id int64) (*User, error)
	GetByEmail(ctx context.Context, email string) (*User, error)
	FindOne(ctx context.Context, filter []UserFilter, sorting []UserSorting) (*User, error)
	Find(ctx context.Context, filter []UserFilter, sorting []UserSorting, limit int, offset int64) ([]User, int64, error)
	Update(ctx context.Context, obj User, fields []UserField) error
	UpdatePassword(ctx context.Context, id int64, version int64, value string) error
	Delete(ctx context.Context, id int64) error
}

type UserStoreImpl struct {
	*StoreImpl
	fields            map[UserField]string
	findFilters       map[UserField]FilterFieldFn
	qrySelectCountObj func() string
	qrySelectObj      func() string
	qryFromObj        func() string
	scanObj           func(obj *User, rows *sql.Rows) error
	getObj_Roles      func(ctx context.Context, obj User) ([]Role, error)
}

func (r *StoreImpl) User() UserStore {
	robj := &UserStoreImpl{
		StoreImpl:         r,
		qrySelectCountObj: qrySelectCountObj_User,
		qrySelectObj:      qrySelectObj_User,
		qryFromObj:        qryFromObj_User,
		scanObj:           scanObj_User,
	}
	robj.getObj_Roles = func(ctx context.Context, obj User) ([]Role, error) {
		return getObj_User_Roles(robj, ctx, obj)
	}
	robj.fields = make(map[UserField]string)
	robj.fields[UserField_ID] = "id"
	robj.fields[UserField_Email] = "email"
	robj.fields[UserField_Version] = "version"
	robj.fields[UserField_Name] = "name"
	robj.fields[UserField_Password] = "password"
	robj.fields[UserField_Token] = "token"
	robj.fields[UserField_Secret] = "secret"
	robj.fields[UserField_Roles] = "roles"
	robj.fields[UserField_CreatedBy] = "created_by"
	robj.fields[UserField_CreatedAt] = "created_at"
	robj.fields[UserField_UpdatedBy] = "updated_by"
	robj.fields[UserField_UpdatedAt] = "updated_at"
	robj.findFilters = make(map[UserField]FilterFieldFn)
	robj.findFilters[UserField_ID] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresInt(qfilter, args, "obj.id", op, value)
	}
	robj.findFilters[UserField_Email] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresTextLower(qfilter, args, "obj.email", op, value)
	}
	robj.findFilters[UserField_Name] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresText(qfilter, args, "obj.name", op, value)
	}
	robj.findFilters[UserField_CreatedBy] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresInt(qfilter, args, "obj.created_by", op, value)
	}
	robj.findFilters[UserField_CreatedAt] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresTime(qfilter, args, "obj.created_at", op, value)
	}
	robj.findFilters[UserField_UpdatedBy] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresInt(qfilter, args, "obj.updated_by", op, value)
	}
	robj.findFilters[UserField_UpdatedAt] = func(qfilter []string, args []any, op FilterOp, value json.RawMessage) ([]string, []any, error) {
		return filterPostgresTime(qfilter, args, "obj.updated_at", op, value)
	}
	return robj
}
