// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"encoding/json"
	"time"

	"example.com/app-api/util/jsql"
)

// swagger: model Param
type Param struct {
	ID          int64           `json:"id"`
	Group       string          `json:"group_name"`
	Code        string          `json:"code"`
	Value       jsql.NullString `json:"value"`
	Description jsql.NullString `json:"description"`
	UpdatedBy   string          `json:"modified_by"`
	UpdatedAt   time.Time       `json:"modified_date"`
}

type ParamField string

const (
	ParamField_ID          ParamField = "id"
	ParamField_Group       ParamField = "group_name"
	ParamField_Code        ParamField = "code"
	ParamField_Value       ParamField = "value"
	ParamField_Description ParamField = "description"
	ParamField_UpdatedBy   ParamField = "modified_by"
	ParamField_UpdatedAt   ParamField = "modified_date"
)

// swagger: model ParamSorting
type ParamSorting struct {
	Field ParamField `json:"field"`
	Dir   SortDir    `json:"dir"`
}

// swagger: model ParamFilter
type ParamFilter struct {
	Field ParamField      `json:"field"`
	Op    FilterOp        `json:"op"`
	Value json.RawMessage `json:"value"`
}
