// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package model

import (
	"context"
	"database/sql"
	"fmt"
	"log/slog"

	"example.com/app-api/util"
)

func (r *ParamStoreImpl) Get(ctx context.Context, id int64) (*Param, error) {
	qry := "SELECT\n  " + r.qrySelectObj() + "\nFROM\n  " + r.qryFromObj() + "\nWHERE\n" +
		`obj.id = $1`
	var obj Param
	slog.Debug("store.Param.Get", slog.String("qry", qry), slog.Int64("id", id))
	rows, err := r.db.QueryContext(ctx, qry, id)
	if err != nil {
		slog.Error("store.Param.Get", slog.String("qry", qry), slog.Int64("id", id), slog.Any("Error", err))
		return nil, err
	}
	defer rows.Close()
	if rows.Next() {
		err = r.scanObj(&obj, rows)
		if err != nil {
			slog.Error("store.Param.Get.Scan", slog.String("qry", qry), slog.Int64("id", id), slog.Any("Error", err))
			return nil, err
		}
	} else {
		return nil, fmt.Errorf("NOT_FOUND")
	}
	return &obj, err
}

func (r *ParamStoreImpl) GetByPARAM_UNIQUE(ctx context.Context, code string, group_name string) (*Param, error) {
	qry := "SELECT\n  " + r.qrySelectObj() + "\nFROM\n  " + r.qryFromObj() + "\nWHERE\n  " +
		`obj.code = $1 AND
      obj.group_name = $2`
	var obj Param
	slog.Debug("store.PARAM_UNIQUE.Get", slog.String("qry", qry), slog.String("code", code), slog.String("group_name", group_name))
	rows, err := r.db.QueryContext(ctx, qry, code, group_name)
	if err != nil {
		slog.Error("store.PARAM_UNIQUE.Get", slog.String("qry", qry), slog.String("code", code), slog.String("group_name", group_name), slog.Any("Error", err))
		return nil, err
	}
	defer rows.Close()
	if rows.Next() {
		err = r.scanObj(&obj, rows)
		if err != nil {
			slog.Error("store.PARAM_UNIQUE.Get", slog.String("qry", qry), slog.String("code", code), slog.String("group_name", group_name), slog.Any("Error", err))
			return nil, err
		}
	} else {
		return nil, fmt.Errorf("NOT_FOUND")
	}
	return &obj, nil
}

func qrySelectCountObj_Param() string {
	return `COUNT(DISTINCT
  obj.id)`
}

func qrySelectObj_Param() string {
	return `obj.id,
      obj.group_name,
      obj.code,
      obj.value,
      obj.description,
      obj.modified_by,
      obj.modified_date`
}

func qryFromObj_Param() string {
	return `param obj`
}

func scanObj_Param(obj *Param, rows *sql.Rows) error {
	var err error

	err = rows.Scan(
		&obj.ID,
		&obj.Group,
		&obj.Code,
		&obj.Value,
		&obj.Description,
		&obj.UpdatedBy,
		&obj.UpdatedAt)
	if err != nil {
		return err
	}
	obj.UpdatedAt = util.AsZoneWallClock(obj.UpdatedAt)
	return err
}
