-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-11-03T03:51:54Z
-- DB: db

CREATE TABLE app_user (
    id BIGSERIAL,
    email TEXT NOT NULL,
    version INTEGER NOT NULL,
    name TEXT NOT NULL,
    password VARCHAR(2000) NOT NULL,
    token VARCHAR(2000),
    secret VARCHAR(2000),
    created_by INTEGER,
    created_at TIMESTAMP NOT NULL,
    updated_by INTEGER,
    updated_at TIMESTAMP NOT NULL,
    FOREIGN KEY(created_by) REFERENCES app_user(id),
    FOREIGN KEY(updated_by) REFERENCES app_user(id),
    PRIMARY KEY (id)
);

ALTER TABLE app_user ADD CONSTRAINT Email UNIQUE (email);

