-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-11-03T03:51:54Z
-- DB: db

CREATE TABLE app_role (
    id BIGSERIAL,
    name TEXT NOT NULL,
    description TEXT,
    privileges JSONB NOT NULL,
    modified_by TEXT NOT NULL,
    modified_date TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE app_role ADD CONSTRAINT Name UNIQUE (name);

