-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-11-03T03:51:54Z
-- DB: db

CREATE TABLE param (
    id BIGSERIAL,
    group_name TEXT NOT NULL,
    code TEXT NOT NULL,
    value TEXT,
    description TEXT,
    modified_by TEXT NOT NULL,
    modified_date TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE param ADD CONSTRAINT PARAM_UNIQUE UNIQUE (code, group_name);

