-- Code generated by apigen. DO NOT EDIT.
-- GENERATED: 2025-11-03T03:51:54Z
-- DB: db


CREATE TABLE app_user_role (
    app_user INTEGER NOT NULL,
    app_role INTEGER NOT NULL,
    FOREIGN KEY (app_user) REFERENCES app_user (id),
    FOREIGN KEY (app_role) REFERENCES app_role (id)
);

