// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package util

import (
	"database/sql"
	"log/slog"
	"os"
	"strings"
	"time"

	_ "github.com/lib/pq"
)

func GetPostgresConn(prefix string) *sql.DB {
	driver := "postgres"
	dsns := []string{"postgres://"}
	v := os.Getenv(prefix + "_USER")
	if v != "" {
		dsns = append(dsns, v)
	} else {
		slog.Error("Environment variable for database user is not set", "var", prefix+"_USER")
		os.Exit(1)
	}
	v = os.Getenv(prefix + "_PASSWORD")
	if v != "" {
		dsns = append(dsns, ":"+v)
	} else {
		slog.Error("Environment variable for database password is not set", "var", prefix+"_PASSWORD")
		os.Exit(1)
	}
	v = os.Getenv(prefix + "_HOST")
	if v != "" {
		dsns = append(dsns, "@"+v)
	} else {
		slog.Error("Environment variable for database host is not set", "var", prefix+"_HOST")
		os.Exit(1)
	}
	v = os.Getenv(prefix + "_PORT")
	if v != "" {
		dsns = append(dsns, ":"+v)
	}
	v = os.Getenv(prefix + "_NAME")
	if v != "" {
		dsns = append(dsns, "/"+v)
	}
	v = os.Getenv(prefix + "_SSLMMODE")
	if v != "" {
		dsns = append(dsns, "?sslmode="+v)
	} else {
		dsns = append(dsns, "?sslmode=disable")
	}
	dsn := strings.Join(dsns, "")
	db, err := sql.Open(driver, dsn)
	if err != nil {
		for i := 0; i < 30 && err != nil; i++ {
			if i%5 == 0 {
				slog.Debug("Error opening db, retrying...", "error", err)
			}
			time.Sleep(2 * time.Second)
			db, err = sql.Open(driver, dsn)
			if err != nil {
				if strings.Contains(err.Error(), "USERNAME AND/OR PASSWORD INVALID") {
					slog.Error("Error opening db, invalid username or password", "error", err)
					os.Exit(1)
				}
			}
		}
		if err != nil {
			slog.Error("Error opening db", "error", err)
			os.Exit(1)
		}
	}
	err = db.Ping()
	if err != nil {
		for i := 0; i < 30 && err != nil; i++ {
			if i%5 == 0 {
				slog.Debug("Waiting for database to be ready (ping)...")
			}
			time.Sleep(2 * time.Second)
			err = db.Ping()
			if err != nil {
				if strings.Contains(err.Error(), "USERNAME AND/OR PASSWORD INVALID") {
					slog.Error("Error opening db, invalid username or password", "error", err)
					os.Exit(1)
				}
			}
		}
		if err != nil {
			slog.Error("Error pinging db", "error", err)
			os.Exit(1)
		}
	}
	return db
}
