// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"
	"time"

	"example.com/app-api/model"
)

// swagger: model RoleFindParam
type RoleFindParam struct {
	Limit   int                 `json:"limit"`
	Offset  int64               `json:"offset"`
	Filter  []model.RoleFilter  `json:"filter"`
	Sorting []model.RoleSorting `json:"sorting"`
}

// swagger: model RoleUpdateParam
type RoleUpdateParam struct {
	Value  model.Role        `json:"value"`
	Fields []model.RoleField `json:"fields"`
}

func RoleHandlerRegister(mux *http.ServeMux, base string, store model.Store, authenticate Authenticate) {
	mux.HandleFunc("PUT "+base+"/role", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_role", "create") {
			writeForbiden(w)
			return
		}
		if err := RoleCreate(r.Context(), store, w, r); err != nil {
			slog.Warn("error in RoleCreate", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("GET "+base+"/role/{id}", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_role", "read") {
			writeForbiden(w)
			return
		}
		if err := RoleGet(r.Context(), store, w, r); err != nil {
			slog.Warn("error in RoleGet", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("POST "+base+"/role", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_role", "read") {
			writeForbiden(w)
			return
		}
		if err := RoleFind(r.Context(), store, w, r); err != nil {
			slog.Warn("error in RoleFind", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("PATCH "+base+"/role/{id}", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_role", "update") {
			writeForbiden(w)
			return
		}
		if err := RoleUpdate(r.Context(), store, w, r); err != nil {
			slog.Warn("error in RoleUpdate", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("DELETE "+base+"/role/{id}", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_role", "delete") {
			writeForbiden(w)
			return
		}
		if err := RoleDelete(r.Context(), store, w, r); err != nil {
			slog.Warn("error in RoleDelete", "err", err)
			writeInternalError(w, err)
			return
		}
	})
}

// CreateRole   godoc
// @Summary      Create role
// @Description  Create role
// @Tags         role
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        role  body    model.Role  true  "Role object"
// @Success      200  {object}  model.Role
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /role [put]
func RoleCreate(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var obj model.Role
	err := json.NewDecoder(r.Body).Decode(&obj)
	if err != nil {
		slog.Warn("invalid body", "err", err)
		return fmt.Errorf("invalid body")
	}
	obj.UpdatedAt = time.Now()

	res, err := store.Role().Create(ctx, obj)
	if err != nil {
		slog.Warn("error create Role", "obj", obj, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(res)
}

// ShowRole   godoc
// @Summary      Get role By PK
// @Description  Get role By PK
// @Tags         role
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      integer  true  "Role ID"
// @Success      200  {object}  model.Role
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /role/{id} [get]
func RoleGet(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	pid := r.PathValue("id")
	id, err := strconv.ParseInt(pid, 10, 64)
	if err != nil {
		slog.Warn("invalid id", "id", pid, "err", err)
		return fmt.Errorf("invalid id")
	}
	obj, err := store.Role().Get(ctx, id)
	if err != nil {
		slog.Warn("error get Role", "id", id, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(obj)
}

// FindRole   godoc
// @Summary      Find role
// @Description  get string by ID
// @Tags         role
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        param  body    RoleFindParam  true  "Role object"
// @Success      200  {object}  model.Role
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /role [post]
func RoleFind(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var obj RoleFindParam
	err := json.NewDecoder(r.Body).Decode(&obj)
	if err != nil {
		slog.Warn("invalid body", "err", err)
		return fmt.Errorf("invalid body")
	}
	var result struct {
		List  []model.Role `json:"list"`
		Total int64        `json:"total"`
	}
	result.List, result.Total, err = store.Role().Find(ctx, obj.Filter, obj.Sorting, obj.Limit, obj.Offset)
	if err != nil {
		slog.Warn("error find Role", "filter", obj.Filter, "sorting", obj.Sorting, "limit", obj.Limit, "offset", obj.Offset, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(result)
}

// UpdateRole   godoc
// @Summary      Update role
// @Description  Update role
// @Tags         role
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      integer  true  "Role ID"
// @Param        param  body    RoleUpdateParam  true  "Role object"
// @Success      200  {object}  model.Role
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /role/{id} [patch]
func RoleUpdate(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var obj RoleUpdateParam
	err := json.NewDecoder(r.Body).Decode(&obj)
	if err != nil {
		slog.Warn("invalid body", "err", err)
		return fmt.Errorf("invalid body")
	}
	obj.Value.UpdatedAt = time.Now()
	obj.Fields = append(obj.Fields, model.RoleField_UpdatedAt)

	pid := r.PathValue("id")
	id, err := strconv.ParseInt(pid, 10, 64)
	if err != nil {
		slog.Warn("invalid id", "id", pid, "err", err)
		return fmt.Errorf("invalid id")
	}
	obj.Value.ID = id
	err = store.Role().Update(ctx, obj.Value, obj.Fields)
	if err != nil {
		slog.Warn("error update Role", "obj", obj, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(obj.Value)
}

// DeleteRole   godoc
// @Summary      Delete role
// @Description  Delete
// @Tags         role
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      integer  true  "Role ID"
// @Success      200  {object}  any
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /role/{id} [delete]
func RoleDelete(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var err error
	pid := r.PathValue("id")
	id, err := strconv.ParseInt(pid, 10, 64)
	if err != nil {
		slog.Warn("invalid id", "id", pid, "err", err)
		return fmt.Errorf("invalid id")
	}
	err = store.Role().Delete(ctx, id)
	if err != nil {
		slog.Warn("error get Role", "id", id, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
}
