// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"
	"time"

	"example.com/app-api/model"
)

// swagger: model UserFindParam
type UserFindParam struct {
	Limit   int                 `json:"limit"`
	Offset  int64               `json:"offset"`
	Filter  []model.UserFilter  `json:"filter"`
	Sorting []model.UserSorting `json:"sorting"`
}

// swagger: model UserUpdateParam
type UserUpdateParam struct {
	Value  model.User        `json:"value"`
	Fields []model.UserField `json:"fields"`
}

func UserHandlerRegister(mux *http.ServeMux, base string, store model.Store, authenticate Authenticate) {
	mux.HandleFunc("PUT "+base+"/user", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_user", "create") {
			writeForbiden(w)
			return
		}
		if err := UserCreate(r.Context(), store, w, r); err != nil {
			slog.Warn("error in UserCreate", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("GET "+base+"/user/{id}", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_user", "read") {
			writeForbiden(w)
			return
		}
		if err := UserGet(r.Context(), store, w, r); err != nil {
			slog.Warn("error in UserGet", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("POST "+base+"/user", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_user", "read") {
			writeForbiden(w)
			return
		}
		if err := UserFind(r.Context(), store, w, r); err != nil {
			slog.Warn("error in UserFind", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("PATCH "+base+"/user/{id}", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_user", "update") {
			writeForbiden(w)
			return
		}
		if err := UserUpdate(r.Context(), store, w, r); err != nil {
			slog.Warn("error in UserUpdate", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("DELETE "+base+"/user/{id}", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "app_user", "delete") {
			writeForbiden(w)
			return
		}
		if err := UserDelete(r.Context(), store, w, r); err != nil {
			slog.Warn("error in UserDelete", "err", err)
			writeInternalError(w, err)
			return
		}
	})
}

// CreateUser   godoc
// @Summary      Create user
// @Description  Create user
// @Tags         user
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        user  body    model.User  true  "User object"
// @Success      200  {object}  model.User
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /user [put]
func UserCreate(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var obj model.User
	err := json.NewDecoder(r.Body).Decode(&obj)
	if err != nil {
		slog.Warn("invalid body", "err", err)
		return fmt.Errorf("invalid body")
	}
	if user, ok := ctx.Value(HandlerCtxKeyUser).(*LoginUser); ok && user.User != nil {
		obj.CreatedBy = &model.UserRef{
			ID: user.User.ID,
		}
	} else {
		return fmt.Errorf("missing user in context")
	}
	obj.CreatedAt = time.Now()
	if user, ok := ctx.Value(HandlerCtxKeyUser).(*LoginUser); ok && user.User != nil {
		obj.UpdatedBy = &model.UserRef{
			ID: user.User.ID,
		}
	} else {
		return fmt.Errorf("missing user in context")
	}
	obj.UpdatedAt = time.Now()

	res, err := store.User().Create(ctx, obj)
	if err != nil {
		slog.Warn("error create User", "obj", obj, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(res)
}

// ShowUser   godoc
// @Summary      Get user By PK
// @Description  Get user By PK
// @Tags         user
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      integer  true  "User ID"
// @Success      200  {object}  model.User
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /user/{id} [get]
func UserGet(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	pid := r.PathValue("id")
	id, err := strconv.ParseInt(pid, 10, 64)
	if err != nil {
		slog.Warn("invalid id", "id", pid, "err", err)
		return fmt.Errorf("invalid id")
	}
	obj, err := store.User().Get(ctx, id)
	if err != nil {
		slog.Warn("error get User", "id", id, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(obj)
}

// FindUser   godoc
// @Summary      Find user
// @Description  get string by ID
// @Tags         user
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        param  body    UserFindParam  true  "User object"
// @Success      200  {object}  model.User
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /user [post]
func UserFind(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var obj UserFindParam
	err := json.NewDecoder(r.Body).Decode(&obj)
	if err != nil {
		slog.Warn("invalid body", "err", err)
		return fmt.Errorf("invalid body")
	}
	var result struct {
		List  []model.User `json:"list"`
		Total int64        `json:"total"`
	}
	result.List, result.Total, err = store.User().Find(ctx, obj.Filter, obj.Sorting, obj.Limit, obj.Offset)
	if err != nil {
		slog.Warn("error find User", "filter", obj.Filter, "sorting", obj.Sorting, "limit", obj.Limit, "offset", obj.Offset, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(result)
}

// UpdateUser   godoc
// @Summary      Update user
// @Description  Update user
// @Tags         user
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      integer  true  "User ID"
// @Param        param  body    UserUpdateParam  true  "User object"
// @Success      200  {object}  model.User
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /user/{id} [patch]
func UserUpdate(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var obj UserUpdateParam
	err := json.NewDecoder(r.Body).Decode(&obj)
	if err != nil {
		slog.Warn("invalid body", "err", err)
		return fmt.Errorf("invalid body")
	}
	if user, ok := ctx.Value(HandlerCtxKeyUser).(*LoginUser); ok && user.User != nil {
		obj.Value.UpdatedBy = &model.UserRef{
			ID: user.User.ID,
		}
		obj.Fields = append(obj.Fields, model.UserField_UpdatedBy)
	} else {
		return fmt.Errorf("missing user in context")
	}
	obj.Value.UpdatedAt = time.Now()
	obj.Fields = append(obj.Fields, model.UserField_UpdatedAt)

	pid := r.PathValue("id")
	id, err := strconv.ParseInt(pid, 10, 64)
	if err != nil {
		slog.Warn("invalid id", "id", pid, "err", err)
		return fmt.Errorf("invalid id")
	}
	obj.Value.ID = id
	err = store.User().Update(ctx, obj.Value, obj.Fields)
	if err != nil {
		slog.Warn("error update User", "obj", obj, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(obj.Value)
}

// DeleteUser   godoc
// @Summary      Delete user
// @Description  Delete
// @Tags         user
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      integer  true  "User ID"
// @Success      200  {object}  any
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /user/{id} [delete]
func UserDelete(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var err error
	pid := r.PathValue("id")
	id, err := strconv.ParseInt(pid, 10, 64)
	if err != nil {
		slog.Warn("invalid id", "id", pid, "err", err)
		return fmt.Errorf("invalid id")
	}
	err = store.User().Delete(ctx, id)
	if err != nil {
		slog.Warn("error get User", "id", id, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
}
