// Code generated by apigen. DO NOT EDIT.
// GENERATED: 2025-11-03T03:51:54Z

package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strconv"
	"time"

	"example.com/app-api/model"
)

// swagger: model ParamFindParam
type ParamFindParam struct {
	Limit   int                  `json:"limit"`
	Offset  int64                `json:"offset"`
	Filter  []model.ParamFilter  `json:"filter"`
	Sorting []model.ParamSorting `json:"sorting"`
}

// swagger: model ParamUpdateParam
type ParamUpdateParam struct {
	Value  model.Param        `json:"value"`
	Fields []model.ParamField `json:"fields"`
}

func ParamHandlerRegister(mux *http.ServeMux, base string, store model.Store, authenticate Authenticate) {
	mux.HandleFunc("PUT "+base+"/param", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "param", "create") {
			writeForbiden(w)
			return
		}
		if err := ParamCreate(r.Context(), store, w, r); err != nil {
			slog.Warn("error in ParamCreate", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("GET "+base+"/param/{id}", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "param", "read") {
			writeForbiden(w)
			return
		}
		if err := ParamGet(r.Context(), store, w, r); err != nil {
			slog.Warn("error in ParamGet", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("POST "+base+"/param", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "param", "read") {
			writeForbiden(w)
			return
		}
		if err := ParamFind(r.Context(), store, w, r); err != nil {
			slog.Warn("error in ParamFind", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("PATCH "+base+"/param/{id}", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "param", "update") {
			writeForbiden(w)
			return
		}
		if err := ParamUpdate(r.Context(), store, w, r); err != nil {
			slog.Warn("error in ParamUpdate", "err", err)
			writeInternalError(w, err)
			return
		}
	})
	mux.HandleFunc("DELETE "+base+"/param/{id}", func(w http.ResponseWriter, r *http.Request) {
		if !authenticate(r, "param", "delete") {
			writeForbiden(w)
			return
		}
		if err := ParamDelete(r.Context(), store, w, r); err != nil {
			slog.Warn("error in ParamDelete", "err", err)
			writeInternalError(w, err)
			return
		}
	})
}

// CreateParam   godoc
// @Summary      Create param
// @Description  Create param
// @Tags         param
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        param  body    model.Param  true  "Param object"
// @Success      200  {object}  model.Param
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /param [put]
func ParamCreate(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var obj model.Param
	err := json.NewDecoder(r.Body).Decode(&obj)
	if err != nil {
		slog.Warn("invalid body", "err", err)
		return fmt.Errorf("invalid body")
	}
	obj.UpdatedAt = time.Now()

	res, err := store.Param().Create(ctx, obj)
	if err != nil {
		slog.Warn("error create Param", "obj", obj, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(res)
}

// ShowParam   godoc
// @Summary      Get param By PK
// @Description  Get param By PK
// @Tags         param
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      integer  true  "Param ID"
// @Success      200  {object}  model.Param
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /param/{id} [get]
func ParamGet(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	pid := r.PathValue("id")
	id, err := strconv.ParseInt(pid, 10, 64)
	if err != nil {
		slog.Warn("invalid id", "id", pid, "err", err)
		return fmt.Errorf("invalid id")
	}
	obj, err := store.Param().Get(ctx, id)
	if err != nil {
		slog.Warn("error get Param", "id", id, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(obj)
}

// FindParam   godoc
// @Summary      Find param
// @Description  get string by ID
// @Tags         param
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        param  body    ParamFindParam  true  "Param object"
// @Success      200  {object}  model.Param
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /param [post]
func ParamFind(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var obj ParamFindParam
	err := json.NewDecoder(r.Body).Decode(&obj)
	if err != nil {
		slog.Warn("invalid body", "err", err)
		return fmt.Errorf("invalid body")
	}
	var result struct {
		List  []model.Param `json:"list"`
		Total int64         `json:"total"`
	}
	result.List, result.Total, err = store.Param().Find(ctx, obj.Filter, obj.Sorting, obj.Limit, obj.Offset)
	if err != nil {
		slog.Warn("error find Param", "filter", obj.Filter, "sorting", obj.Sorting, "limit", obj.Limit, "offset", obj.Offset, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(result)
}

// UpdateParam   godoc
// @Summary      Update param
// @Description  Update param
// @Tags         param
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      integer  true  "Param ID"
// @Param        param  body    ParamUpdateParam  true  "Param object"
// @Success      200  {object}  model.Param
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /param/{id} [patch]
func ParamUpdate(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var obj ParamUpdateParam
	err := json.NewDecoder(r.Body).Decode(&obj)
	if err != nil {
		slog.Warn("invalid body", "err", err)
		return fmt.Errorf("invalid body")
	}
	obj.Value.UpdatedAt = time.Now()
	obj.Fields = append(obj.Fields, model.ParamField_UpdatedAt)

	pid := r.PathValue("id")
	id, err := strconv.ParseInt(pid, 10, 64)
	if err != nil {
		slog.Warn("invalid id", "id", pid, "err", err)
		return fmt.Errorf("invalid id")
	}
	obj.Value.ID = id
	err = store.Param().Update(ctx, obj.Value, obj.Fields)
	if err != nil {
		slog.Warn("error update Param", "obj", obj, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(obj.Value)
}

// DeleteParam   godoc
// @Summary      Delete param
// @Description  Delete
// @Tags         param
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id   path      integer  true  "Param ID"
// @Success      200  {object}  any
// @Failure      400  {object}  HttpResult
// @Failure      404  {object}  HttpResult
// @Failure      500  {object}  HttpResult
// @Router       /param/{id} [delete]
func ParamDelete(ctx context.Context, store model.Store, w http.ResponseWriter, r *http.Request) error {
	var err error
	pid := r.PathValue("id")
	id, err := strconv.ParseInt(pid, 10, 64)
	if err != nil {
		slog.Warn("invalid id", "id", pid, "err", err)
		return fmt.Errorf("invalid id")
	}
	err = store.Param().Delete(ctx, id)
	if err != nil {
		slog.Warn("error get Param", "id", id, "err", err)
		return err
	}
	return json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
}
